# Generated by Django 6.0.4 on 2026-06-28 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttackType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text='Stored on alerts and used in response mappings, e.g. sql_injection', unique=True)),
                ('name', models.CharField(max_length=100)),
                ('keywords', models.JSONField(blank=True, default=list, help_text='Lowercase substrings matched against the Wazuh rule description, e.g. ["sql injection", "sqli"]. First matching attack type wins.')),
                ('base_score', models.PositiveIntegerField(default=20, help_text='0-100 base score before the Wazuh rule-level bonus is added')),
                ('priority', models.IntegerField(default=100, help_text='Lower is checked first when matching keywords (specific before generic)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['priority', 'key'],
            },
        ),
    ]
