# Generated by Django 6.0.4 on 2026-06-28 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponseDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('handler_key', models.CharField(help_text='Key of a registered response handler (e.g. block_ip, kill_process, notify)', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('params', models.JSONField(blank=True, default=dict, help_text='Default params passed to the handler, e.g. {"duration_hours": 24}')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='responseaction',
            name='action_type',
            field=models.CharField(help_text='handler_key that was run', max_length=50),
        ),
        migrations.AlterField(
            model_name='responseaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('executed', 'Executed'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='responseaction',
            name='response_definition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executions', to='responses.responsedefinition'),
        ),
        migrations.CreateModel(
            name='AttackResponseMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attack_type', models.CharField(choices=[('web_attack', 'Web Attack'), ('brute_force', 'Brute Force'), ('sql_injection', 'SQL Injection'), ('xss', 'XSS'), ('traversal', 'Directory Traversal'), ('command_injection', 'Command Injection'), ('scanning', 'Scanning'), ('dos', 'DoS'), ('malware', 'Malware'), ('unknown', 'Unknown')], max_length=50)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower runs first')),
                ('params_override', models.JSONField(blank=True, default=dict, help_text="Optional params merged over the response's defaults")),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='responses.responsedefinition')),
            ],
            options={
                'ordering': ['attack_type', 'order'],
                'unique_together': {('attack_type', 'response')},
            },
        ),
    ]
