# Generated by Django 6.0.4 on 2026-06-28 00:47

from django.db import migrations


# Default response catalog: name -> (handler_key, params, description)
DEFINITIONS = {
    'Block IP (24h)':   ('block_ip', {'duration_hours': 24}, 'Block the source IP via iptables for 24 hours'),
    'Block IP (1h)':    ('block_ip', {'duration_hours': 1},  'Block the source IP via iptables for 1 hour'),
    'Kill Processes':   ('kill_process', {}, 'Terminate suspicious processes'),
    'Notify':           ('notify', {}, 'Log + optional webhook notification'),
}

# attack_type -> [(definition_name, order), ...]
MAPPINGS = {
    'sql_injection':     [('Block IP (24h)', 0), ('Notify', 1)],
    'command_injection': [('Block IP (24h)', 0), ('Notify', 1)],
    'traversal':         [('Block IP (24h)', 0), ('Notify', 1)],
    'xss':               [('Block IP (24h)', 0), ('Notify', 1)],
    'brute_force':       [('Block IP (24h)', 0), ('Notify', 1)],
    'dos':               [('Block IP (24h)', 0), ('Notify', 1)],
    'web_attack':        [('Block IP (1h)', 0),  ('Notify', 1)],
    'scanning':          [('Notify', 0)],
    'malware':           [('Kill Processes', 0), ('Notify', 1)],
    'unknown':           [('Notify', 0)],
}


def seed(apps, schema_editor):
    ResponseDefinition = apps.get_model('responses', 'ResponseDefinition')
    AttackResponseMap  = apps.get_model('responses', 'AttackResponseMap')

    defs = {}
    for name, (handler_key, params, desc) in DEFINITIONS.items():
        defs[name], _ = ResponseDefinition.objects.get_or_create(
            name=name,
            defaults={'handler_key': handler_key, 'params': params, 'description': desc},
        )

    for attack_type, items in MAPPINGS.items():
        for def_name, order in items:
            AttackResponseMap.objects.get_or_create(
                attack_type=attack_type,
                response=defs[def_name],
                defaults={'order': order},
            )


def unseed(apps, schema_editor):
    ResponseDefinition = apps.get_model('responses', 'ResponseDefinition')
    AttackResponseMap  = apps.get_model('responses', 'AttackResponseMap')
    AttackResponseMap.objects.all().delete()
    ResponseDefinition.objects.filter(name__in=DEFINITIONS.keys()).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('responses', '0002_responsedefinition_alter_responseaction_action_type_and_more'),
    ]

    operations = [
        migrations.RunPython(seed, unseed),
    ]
