# Generated by Django 6.0.4 on 2026-06-28 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_alter_alert_attack_type'),
        ('responses', '0003_seed_default_responses'),
    ]

    operations = [
        migrations.AddField(
            model_name='responseaction',
            name='trigger',
            field=models.CharField(choices=[('auto', 'Automatic'), ('manual', 'Manual')], default='auto', max_length=10),
        ),
        migrations.AlterField(
            model_name='responseaction',
            name='alert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='alerts.alert'),
        ),
    ]
