# Generated by Django 6.0.4 on 2026-06-28 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responses', '0004_responseaction_trigger_alter_responseaction_alert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attackresponsemap',
            name='attack_type',
            field=models.CharField(help_text='AttackType.key this mapping responds to', max_length=50),
        ),
    ]
