# Generated by Django 6.0.4 on 2026-06-28 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responses', '0005_alter_attackresponsemap_attack_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responseaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('executed', 'Executed'), ('failed', 'Failed'), ('skipped', 'Skipped'), ('revoked', 'Revoked')], default='pending', max_length=20),
        ),
    ]
