# Generated by Django 6.0.4 on 2026-04-22 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetectionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('severity_default', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=10)),
                ('is_custom', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='IPProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('total_events', models.IntegerField(default=0)),
                ('events_last_hour', models.IntegerField(default=0)),
                ('events_last_24h', models.IntegerField(default=0)),
                ('is_blocked', models.BooleanField(default=False)),
                ('blocked_at', models.DateTimeField(blank=True, null=True)),
                ('blocked_reason', models.TextField(blank=True, null=True)),
                ('threat_score', models.IntegerField(default=0)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('asn', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['-threat_score'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wazuh_alert_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('timestamp', models.DateTimeField()),
                ('rule_id', models.IntegerField()),
                ('rule_description', models.TextField()),
                ('rule_level', models.IntegerField()),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('destination_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('agent_id', models.CharField(blank=True, max_length=20, null=True)),
                ('agent_name', models.CharField(blank=True, max_length=100, null=True)),
                ('attack_type', models.CharField(choices=[('web_attack', 'Web Attack'), ('brute_force', 'Brute Force'), ('sql_injection', 'SQL Injection'), ('xss', 'XSS'), ('traversal', 'Directory Traversal'), ('dos', 'DoS'), ('malware', 'Malware'), ('unknown', 'Unknown')], default='unknown', max_length=50)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=10)),
                ('raw_log', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('new', 'New'), ('processing', 'Processing'), ('resolved', 'Resolved')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['severity'], name='alerts_aler_severit_202179_idx'), models.Index(fields=['source_ip'], name='alerts_aler_source__c35806_idx'), models.Index(fields=['attack_type'], name='alerts_aler_attack__a6fff7_idx'), models.Index(fields=['timestamp'], name='alerts_aler_timesta_c1e3bc_idx'), models.Index(fields=['status'], name='alerts_aler_status_2a92cb_idx')],
            },
        ),
    ]
