# Generated by Django 6.0.4 on 2026-06-28 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='attack_type',
            field=models.CharField(choices=[('web_attack', 'Web Attack'), ('brute_force', 'Brute Force'), ('sql_injection', 'SQL Injection'), ('xss', 'XSS'), ('traversal', 'Directory Traversal'), ('command_injection', 'Command Injection'), ('scanning', 'Scanning'), ('dos', 'DoS'), ('malware', 'Malware'), ('unknown', 'Unknown')], default='unknown', max_length=50),
        ),
    ]
