# Generated by Django 6.0.4 on 2026-06-28 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_alter_alert_attack_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='attack_type',
            field=models.CharField(default='unknown', max_length=50),
        ),
    ]
